<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Orleans.FSharp" Version="4.*" />
    <PackageReference Include="Orleans.FSharp.Runtime" Version="4.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyApp.Grains\MyApp.Grains.fsproj" />
  </ItemGroup>

</Project>
