// Backward-compatible concrete grain implementations for the Orleans.FSharp.Sample project.
// These classes exist so Orleans source generators can produce grain metadata for the
// per-grain F# interfaces used in the legacy pattern.
//
// NOTE: In the new universal interface pattern, users reference Orleans.FSharp.Abstractions
// and call grains via IFSharpGrain + FSharpGrainHandle — no per-grain C# stubs needed.
// These stubs are only here to keep the sample project and integration tests working.
//
// Each impl delegates all behavior to its corresponding F# GrainDefinition.

#pragma warning disable CS1591

using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Orleans;
using Orleans.Concurrency;
using Orleans.EventSourcing;
using Orleans.Providers;
using Orleans.Runtime;
using Orleans.FSharp;
using Orleans.FSharp.Runtime;
using Orleans.FSharp.Sample;
using Orleans.FSharp.EventSourcing;
using Orleans.Transactions.Abstractions;

namespace Orleans.FSharp.CodeGen;

// ─── Counter ───────────────────────────────────────────────────────────────

public class CounterGrainImpl : Grain, ICounterGrain
{
    private readonly IPersistentState<CounterStateHolder> _state;
    private readonly ILogger<CounterGrainImpl> _logger;
    private CounterState _current;

    public CounterGrainImpl(
        [PersistentState("state", "Default")] IPersistentState<CounterStateHolder> state,
        ILogger<CounterGrainImpl> logger)
    { _state = state; _logger = logger; _current = CounterGrainDef.counter.DefaultState.Value; }

    public override Task OnActivateAsync(CancellationToken ct)
    {
        if (_state.RecordExists) _current = _state.State.State;
        return Task.CompletedTask;
    }

    public async Task<object> HandleMessage(CounterCommand cmd)
    {
        var (next, result) = await GrainDefinition.invokeHandler(CounterGrainDef.counter, _current, cmd);
        _current = next; _state.State.State = next; await _state.WriteStateAsync();
        return result;
    }
}

// ─── Echo ───────────────────────────────────────────────────────────────────

public class EchoGrainImpl : Grain, IEchoGrain
{
    private readonly ILogger<EchoGrainImpl> _logger;
    private string _current = "";

    public EchoGrainImpl(ILogger<EchoGrainImpl> logger) => _logger = logger;

    public override Task OnActivateAsync(CancellationToken ct)
    { _current = this.GetPrimaryKeyString(); return Task.CompletedTask; }

    public async Task<object> HandleMessage(EchoCommand cmd)
    {
        var (next, result) = await GrainDefinition.invokeHandler(EchoGrainDef.echo, _current, cmd);
        _current = next; return result;
    }
}

// ─── Order ──────────────────────────────────────────────────────────────────

public class OrderGrainImpl : Grain, IOrderGrain
{
    private readonly IPersistentState<OrderStatusHolder> _state;
    private readonly ILogger<OrderGrainImpl> _logger;
    private OrderStatus _current;

    public OrderGrainImpl(
        [PersistentState("state", "Default")] IPersistentState<OrderStatusHolder> state,
        ILogger<OrderGrainImpl> logger)
    { _state = state; _logger = logger; _current = OrderGrainDef.order.DefaultState.Value; }

    public override Task OnActivateAsync(CancellationToken ct)
    { if (_state.RecordExists) _current = _state.State.State; return Task.CompletedTask; }

    public async Task<object> HandleMessage(OrderCommand cmd)
    {
        var (next, result) = await GrainDefinition.invokeHandler(OrderGrainDef.order, _current, cmd);
        _current = next; _state.State.State = next; await _state.WriteStateAsync();
        return result;
    }
}

// ─── BankAccount: generated by Orleans.FSharp.Generator (see Generated/BankAccountGrainImpl.g.cs) ───

// ─── Processor (stateless worker) ───────────────────────────────────────────

[StatelessWorker(4)]
public class ProcessorGrainImpl : Grain, IProcessorGrain
{
    private readonly ILogger<ProcessorGrainImpl> _logger;
    private string _current = Guid.NewGuid().ToString();

    public ProcessorGrainImpl(ILogger<ProcessorGrainImpl> logger) => _logger = logger;

    public async Task<object> HandleMessage(ProcessorCommand cmd)
    {
        var (next, result) = await GrainDefinition.invokeHandler(ProcessorGrainDef.processor, _current, cmd);
        _current = next; return result;
    }
}

// ─── ReminderTest ───────────────────────────────────────────────────────────

public class ReminderTestGrainImpl : Grain, IReminderTestGrain, IRemindable
{
    private readonly IPersistentState<ReminderStateHolder> _state;
    private readonly ILogger<ReminderTestGrainImpl> _logger;
    private int _current;

    public ReminderTestGrainImpl(
        [PersistentState("state", "Default")] IPersistentState<ReminderStateHolder> state,
        ILogger<ReminderTestGrainImpl> logger)
    { _state = state; _logger = logger; _current = ReminderTestGrainDef.reminderTestGrain.DefaultState.Value; }

    public override Task OnActivateAsync(CancellationToken ct)
    { if (_state.RecordExists) _current = _state.State.ReminderFireCount; return Task.CompletedTask; }

    public async Task<object> HandleMessage(ReminderCommand cmd)
    {
        if (cmd.IsGetFireCount)
            return (object)_current;
        if (cmd is ReminderCommand.RegisterReminder reg)
        {
            await this.RegisterOrUpdateReminder(reg.name, TimeSpan.FromSeconds(1), TimeSpan.FromSeconds(2));
            return (object)true;
        }
        if (cmd is ReminderCommand.UnregisterReminder unreg)
        {
            try { var r = await this.GetReminder(unreg.name); if (r != null) await this.UnregisterReminder(r); }
            catch { /* reminder may not exist */ }
            return (object)true;
        }
        return (object)_current;
    }

    public async Task ReceiveReminder(string reminderName, TickStatus status)
    {
        _current = await GrainDefinition.invokeReminderHandler(ReminderTestGrainDef.reminderTestGrain, _current, reminderName, status);
        _state.State.ReminderFireCount = _current;
        await _state.WriteStateAsync();
    }
}

// ─── TimerTest ──────────────────────────────────────────────────────────────

public class TimerTestGrainImpl : Grain, ITimerTestGrain
{
    private readonly ILogger<TimerTestGrainImpl> _logger;
    private int _current;

    public TimerTestGrainImpl(ILogger<TimerTestGrainImpl> logger)
    { _logger = logger; _current = TimerTestGrainDef.timerTestGrain.DefaultState.Value; }

    public override Task OnActivateAsync(CancellationToken ct)
    {
        foreach (var kvp in TimerTestGrainDef.timerTestGrain.TimerHandlers)
        {
            var (dueTime, period, handler) = kvp.Value;
            this.RegisterGrainTimer(
                async (object? _, CancellationToken _) => { _current = await handler.Invoke(_current); },
                null,
                new GrainTimerCreationOptions { DueTime = dueTime, Period = period });
        }
        return Task.CompletedTask;
    }

    public async Task<object> HandleMessage(TimerCommand cmd)
    {
        var (next, result) = await GrainDefinition.invokeHandler(TimerTestGrainDef.timerTestGrain, _current, cmd);
        _current = next; return result;
    }
}

// ─── Sequential ─────────────────────────────────────────────────────────────

public class SequentialGrainImpl : Grain, ISequentialGrain
{
    private readonly ILogger<SequentialGrainImpl> _logger;
    private int _current;

    public SequentialGrainImpl(ILogger<SequentialGrainImpl> logger)
    { _logger = logger; _current = SequentialGrainDef.sequential.DefaultState.Value; }

    public async Task<object> HandleMessage(SequentialCommand cmd)
    {
        var (next, result) = await GrainDefinition.invokeHandler(SequentialGrainDef.sequential, _current, cmd);
        _current = next; return result;
    }
}

// ─── Aggregator ─────────────────────────────────────────────────────────────

[Reentrant]
public class AggregatorGrainImpl : Grain, IAggregatorGrain
{
    private readonly ILogger<AggregatorGrainImpl> _logger;
    private int _current;

    public AggregatorGrainImpl(ILogger<AggregatorGrainImpl> logger)
    { _logger = logger; _current = AggregatorGrainDef.aggregator.DefaultState.Value; }

    public async Task<object> HandleMessage(AggregatorCommand cmd)
    {
        var (next, result) = await GrainDefinition.invokeHandler(AggregatorGrainDef.aggregator, _current, cmd);
        _current = next; return result;
    }
}

// ─── ObserverTest ────────────────────────────────────────────────────────────

// ─── LifecycleTest ──────────────────────────────────────────────────────────

/// <summary>
/// Concrete grain implementation for the lifecycle-hook test grain.
/// Inherits from <see cref="Grain"/> (NOT from the generic
/// <c>Orleans.FSharp.Runtime.FSharpGrain&lt;S,M&gt;</c>) so it does not accidentally
/// implement <see cref="IFSharpGrain"/> and conflict with <see cref="FSharpGrainImpl"/>
/// in Orleans' grain-type resolution table.
///
/// Lifecycle hooks (<c>onActivate</c> / <c>onDeactivate</c>) are called manually from
/// <see cref="OnActivateAsync"/> and <see cref="OnDeactivateAsync"/> by inspecting the
/// <c>GrainDefinition</c>'s <c>OnActivate</c> and <c>OnDeactivate</c> option fields,
/// exercising the same code path that <c>FSharpGrain&lt;S,M&gt;</c> uses internally.
/// </summary>
public class LifecycleTestGrainImpl : Grain, ILifecycleTestGrain
{
    private readonly GrainDefinition<LifecycleState, LifecycleTestCommand> _def;
    private readonly IPersistentState<LifecycleState> _state;
    private LifecycleState _current;

    /// <summary>
    /// Initialises the grain from DI.
    /// <c>GrainDefinition</c> is registered as a singleton by <c>AddFSharpGrain</c>;
    /// <c>IPersistentState</c> is injected with the "Default" storage provider.
    /// </summary>
    public LifecycleTestGrainImpl(
        GrainDefinition<LifecycleState, LifecycleTestCommand> definition,
        [PersistentState("state", "Default")] IPersistentState<LifecycleState> state)
    {
        _def = definition;
        _state = state;
        _current = definition.DefaultState.Value;
    }

    /// <summary>
    /// Restores persisted state (if any), then invokes the <c>onActivate</c> F# hook
    /// via <see cref="GrainDefinition.invokeOnActivate"/>.
    /// </summary>
    public override async Task OnActivateAsync(CancellationToken ct)
    {
        if (_state.RecordExists)
            _current = _state.State;

        _current = await GrainDefinition.invokeOnActivate(_def, _current);
    }

    /// <summary>
    /// Invokes the <c>onDeactivate</c> F# hook via <see cref="GrainDefinition.invokeOnDeactivate"/>.
    /// </summary>
    public override async Task OnDeactivateAsync(DeactivationReason reason, CancellationToken ct)
    {
        await GrainDefinition.invokeOnDeactivate(_def, _current);
    }

    /// <summary>
    /// Dispatches a lifecycle command to the F# handler, persists the updated state,
    /// and returns the boxed result.
    /// </summary>
    public async Task<object> HandleMessage(LifecycleTestCommand cmd)
    {
        var (next, result) = await GrainDefinition.invokeHandler(_def, _current, cmd);
        _current = next;
        _state.State = _current;
        await _state.WriteStateAsync();
        return result;
    }
}

// ─── AdditionalState ────────────────────────────────────────────────────────

/// <summary>
/// Concrete grain that exercises the <c>additionalState</c> CE keyword end-to-end.
///
/// Holds a primary counter (<see cref="AdditionalState"/>) persisted via <c>IPersistentState</c>
/// and a secondary audit counter (<see cref="AuditState"/>) initialised by
/// <see cref="Orleans.FSharp.Runtime.GrainDefinition.initAdditionalStates{TState,TMessage}"/>.
/// The context-aware F# handler accesses the audit state via
/// <c>GrainContext.getState</c>.
///
/// The grain is intentionally wired via a per-grain C# stub (not <c>FSharpGrainImpl</c>) so that
/// additional-state initialisation in <c>OnActivateAsync</c> can be tested in isolation without
/// interfering with the universal <see cref="Orleans.FSharp.IFSharpGrain"/> dispatch table.
/// </summary>
public class AdditionalStateTestGrainImpl : Grain, IAdditionalStateTestGrain
{
    private readonly GrainDefinition<AdditionalState, AdditionalStateCommand> _def;
    private readonly IPersistentState<AdditionalState> _state;
    private AdditionalState _current;

    // Holds the additional state wrappers after OnActivateAsync, keyed by declared name.
    private System.Collections.Generic.Dictionary<string, object> _additionalStates = new();

    /// <summary>
    /// Initialises the grain from DI.
    /// The <c>GrainDefinition</c> singleton is registered with <c>AddSingleton</c> in the test
    /// fixture (NOT via <c>AddFSharpGrain</c>) to avoid adding the message type to the universal
    /// handler registry, which would cause <c>IFSharpGrain</c> ambiguity.
    /// </summary>
    public AdditionalStateTestGrainImpl(
        GrainDefinition<AdditionalState, AdditionalStateCommand> definition,
        [PersistentState("state", "Default")] IPersistentState<AdditionalState> state)
    {
        _def = definition;
        _state = state;
        _current = definition.DefaultState.Value;
    }

    /// <summary>
    /// Restores the primary state from storage, then initialises all named additional states
    /// declared in the grain definition via
    /// <see cref="Orleans.FSharp.Runtime.GrainDefinition.initAdditionalStates{TState,TMessage}"/>.
    /// </summary>
    public override async Task OnActivateAsync(CancellationToken ct)
    {
        if (_state.RecordExists)
            _current = _state.State;

        _additionalStates = await Orleans.FSharp.Runtime.GrainDefinition.initAdditionalStates(
            _def, ServiceProvider, this.GrainContext.GrainId);
    }

    /// <summary>
    /// Builds a <see cref="Orleans.FSharp.GrainContext"/> from the initialised additional states
    /// and dispatches the command to the F# context-aware handler.
    /// Both primary and additional states are persisted on mutating commands.
    /// </summary>
    public async Task<object> HandleMessage(AdditionalStateCommand cmd)
    {
        // GrainContext module compiles as GrainContextModule in C# (F# appends "Module" suffix
        // when a module shares the same name as a type in the same namespace).
        var ctx = Orleans.FSharp.GrainContextModule.forCSharp(GrainFactory, ServiceProvider, _additionalStates, this.GrainContext.GrainId);
        var (next, result) = await GrainDefinition.invokeContextHandler(_def, ctx, _current, cmd);
        _current = next;
        _state.State = _current;
        await _state.WriteStateAsync();
        return result;
    }
}

/// <summary>
/// Observer interface used by <see cref="ITestChatGrain"/> integration tests.
/// Defined in C# so Orleans source generators produce the required observer proxy.
/// </summary>
public interface ITestChatObserver : IGrainObserver
{
    /// <summary>Called by the grain when a message is broadcast to all subscribers.</summary>
    /// <param name="message">The broadcast message content.</param>
    Task ReceiveMessage(string message);
}

/// <summary>
/// Grain interface for testing <see cref="FSharpObserverManager{T}"/> in an end-to-end cluster.
/// </summary>
public interface ITestChatGrain : IGrainWithStringKey
{
    /// <summary>Registers an observer to receive future broadcasts.</summary>
    Task Subscribe(ITestChatObserver observer);
    /// <summary>Removes an observer from the subscription list.</summary>
    Task Unsubscribe(ITestChatObserver observer);
    /// <summary>Notifies all active subscribers with the given message.</summary>
    Task Broadcast(string message);
    /// <summary>Returns the number of currently active subscribers.</summary>
    Task<int> GetSubscriberCount();
}

/// <summary>
/// Concrete grain that exercises <see cref="FSharpObserverManager{T}"/> in a real cluster.
/// Uses the C#-friendly <c>NotifyAsync</c> overload to dispatch to all subscribers.
/// </summary>
public class TestChatGrainImpl : Grain, ITestChatGrain
{
    private readonly FSharpObserverManager<ITestChatObserver> _manager =
        new FSharpObserverManager<ITestChatObserver>(TimeSpan.FromMinutes(5));

    /// <inheritdoc/>
    public Task Subscribe(ITestChatObserver observer)
    {
        _manager.Subscribe(observer);
        return Task.CompletedTask;
    }

    /// <inheritdoc/>
    public Task Unsubscribe(ITestChatObserver observer)
    {
        _manager.Unsubscribe(observer);
        return Task.CompletedTask;
    }

    /// <inheritdoc/>
    public Task Broadcast(string message) =>
        _manager.NotifyAsync(obs => obs.ReceiveMessage(message));

    /// <inheritdoc/>
    public Task<int> GetSubscriberCount() =>
        Task.FromResult(_manager.Count);
}

// ─── TransactionalAccount ──────────────────────────────────────────────────

/// <summary>
/// Concrete transactional account grain for integration tests.
/// Inherits the generic <see cref="Orleans.FSharp.Runtime.FSharpTransactionalGrain{TState}"/>
/// base, which wires <see cref="Orleans.Transactions.Abstractions.ITransactionalState{T}"/>
/// and delegates all logic to the F# <c>TransactionalGrainDefinition</c> singleton.
/// </summary>
public class TransactionalAccountGrainImpl
    : Orleans.FSharp.Runtime.FSharpTransactionalGrain<Orleans.FSharp.Sample.TransactionalAccountState>,
      Orleans.FSharp.Sample.ITransactionalAccountGrain
{
    public TransactionalAccountGrainImpl(
        [TransactionalState("state", "TransactionStore")] ITransactionalState<Orleans.FSharp.Sample.TransactionalAccountState> state,
        Orleans.FSharp.Runtime.TransactionalGrainDefinition<Orleans.FSharp.Sample.TransactionalAccountState> definition,
        Microsoft.Extensions.Logging.ILogger<Orleans.FSharp.Runtime.FSharpTransactionalGrain<Orleans.FSharp.Sample.TransactionalAccountState>> logger)
        : base(state, definition, logger) { }
}

/// <summary>
/// Concrete ATM grain for integration tests.
/// Inherits the generic <see cref="Orleans.FSharp.Runtime.FSharpAtmGrain{TAccountGrain}"/>
/// base which orchestrates cross-account transfers within a single Orleans transaction.
/// </summary>
public class TransactionalAtmGrainImpl
    : Orleans.FSharp.Runtime.FSharpAtmGrain<Orleans.FSharp.Sample.ITransactionalAccountGrain>,
      Orleans.FSharp.Sample.ITransactionalAtmGrain
{
    public TransactionalAtmGrainImpl(
        Orleans.FSharp.Runtime.AtmGrainDefinition<Orleans.FSharp.Sample.ITransactionalAccountGrain> definition,
        Microsoft.Extensions.Logging.ILogger<Orleans.FSharp.Runtime.FSharpAtmGrain<Orleans.FSharp.Sample.ITransactionalAccountGrain>> logger)
        : base(definition, logger) { }
}

#pragma warning restore CS1591
