namespace SignalRRealtime.Shared

open System

/// <summary>
/// A single metric data point generated by the dashboard grain.
/// </summary>
type MetricEvent =
    {
        /// <summary>The name of the metric (e.g., "cpu", "memory", "requests").</summary>
        Name: string
        /// <summary>The metric value.</summary>
        Value: float
        /// <summary>UTC timestamp when the metric was generated.</summary>
        Timestamp: DateTime
    }

/// <summary>
/// A dashboard update containing multiple metric events.
/// Sent from the grain through SignalR to connected browsers.
/// </summary>
type DashboardUpdate =
    {
        /// <summary>The collection of metric events in this update.</summary>
        Metrics: MetricEvent list
        /// <summary>Sequence number for ordering updates.</summary>
        SequenceNumber: int64
    }
